services:
    powerdns:
        build: .
        ports:
            - 53:53/udp
            - 53:53/tcp
            - 127.0.0.1:8081:8081
        environment:
            - PDNS_LOG_LEVEL=0
            - PDNS_API_KEY=${PDNS_API_KEY}
            - PDNS_WEBSERVER_ALLOWED_FROM=127.0.0.1,::1,172.0.0.0/8
        volumes: 
            - ./pdns/:/pdns/
    dnsadmin:
        image: powerdnsadmin/pda-legacy:latest
        links:
            - "powerdns:powerdns"
        environment: 
            - SQLALCHEMY_DATABASE_URI=sqlite:////pdns/pdns_db.sqlite
            - GUINCORN_TIMEOUT=60
            - SECRET_KEY=${PADM_SECRET_KEY}
            - GUNICORN_WORKERS=2
            - GUNICORN_LOGLEVEL=INFO
        volumes: 
            - ./pdns/:/pdns/
        ports: 
            - 127.0.0.1:8080:80
        logging:
            driver: json-file
            options:
              max-size: 10m
